name: build-docker-image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Handle beta version
        run: |
          if [[ "${{ env.APP_VERSION }}" == *"beta"* ]]; then
            echo APP_TAG=dev >> $GITHUB_ENV
          else
            echo APP_TAG=latest >> $GITHUB_ENV
          fi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6

          build-tags:
            APP_NAME=lrcapi
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/lrcapi:${{ env.APP_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/lrcapi:${{ env.APP_TAG }}
