name: release-build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make_release.py
        run: python make_release.py

      - name: Archive release files
        run: |
          mkdir -p dist
          zip -r release.zip dist

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip